#!/usr/bin/env python3

"""
vct

USAGE

vct dl
vct parse
vct move

"""

if __name__ == "__main__":

    import sys

    if len(sys.argv) < 2:
        print(__doc__)
    elif sys.argv[1] == 'dl':
        from vocaran_tools.scripts import dl
        sys.argv[0] = 'vct dl'
        dl.main(*sys.argv[2:])
    elif sys.argv[1] == 'parse':
        from vocaran_tools.scripts import parse
        sys.argv[0] = 'vct parse'
        parse.main(*sys.argv[2:])
    elif sys.argv[1] == 'move':
        from vocaran_tools.scripts import move_songs
        sys.argv[0] = 'vct move'
        move_songs.main(*sys.argv[2:])
    else:
        print("{} is not valid.".format(sys.argv[1]))
        print(__doc__)
