#!/usr/bin/env python3

"""
vct

USAGE

vct add
vct dl
vct show
vct translate
vct move

"""

import sys

from vocaran_tools.scripts import add
from vocaran_tools.scripts import dl
from vocaran_tools.scripts import show
from vocaran_tools.scripts import translate
from vocaran_tools.scripts import move_songs
from vocaran_tools.errors import ExitException

def main(*args):
    if len(args) < 1:
        print(__doc__)
    elif args[0] == 'add':
        sys.argv[0] = 'vct add'
        add.main(*args[1:])
    elif args[0] == 'dl':
        sys.argv[0] = 'vct dl'
        dl.main(*args[1:])
    elif args[0] == 'show':
        sys.argv[0] = 'vct show'
        show.main(*args[1:])
    elif args[0] == 'translate':
        sys.argv[0] = 'vct translate'
        translate.main(*args[1:])
    elif args[0] == 'move':
        sys.argv[0] = 'vct move_songs'
        move_songs.main(*args[1:])
    else:
        print("{} is not valid.".format(sys.argv[1]))
        print(__doc__)

if __name__ == "__main__":
    try:
        main(*sys.argv[1:])
    except ExitException as e:
        sys.exit(e.code)
